import { Car, Testimonial, EventUseCase } from './types';

export const cars: Car[] = [
  {
    id: '1',
    slug: 'mercedes-e-class',
    name: 'Mercedes-Benz E-Class',
    brand: 'Mercedes-Benz',
    model: 'E 220d',
    year: 2024,
    category: 'sedan',
    eventTypes: ['wedding', 'corporate', 'airport'],
    pricePerDay: 450,
    seats: 5,
    luggage: 2,
    transmission: 'automatic',
    fuelType: 'diesel',
    features: ['Climate Control', 'Leather Seats', 'Bluetooth', 'Sunroof', 'Navigation', 'Apple CarPlay'],
    chauffeurAvailable: true,
    images: [
      '/cars/mercedes-e-class.png',
      '/cars/mercedes-e-class.png',
      '/cars/mercedes-e-class.png',
    ],
    description: 'The 2024 Mercedes-Benz E 220d is the pinnacle of the modern executive saloon. Draped in premium Nappa leather and equipped with the latest MBUX infotainment, every journey becomes a first-class experience. Its refined diesel engine delivers effortless long-range performance — making it the definitive choice for weddings, boardroom arrivals, and VIP airport transfers across Morocco.',
    shortDesc: 'Elegant executive saloon for prestigious occasions.',
    available: true,
  },
  {
    id: '2',
    slug: 'bmw-5-series',
    name: 'BMW 5 Series',
    brand: 'BMW',
    model: '520d',
    year: 2024,
    category: 'sedan',
    eventTypes: ['corporate', 'airport', 'wedding'],
    pricePerDay: 420,
    seats: 5,
    luggage: 2,
    transmission: 'automatic',
    fuelType: 'diesel',
    features: ['Ambient Lighting', 'Heated Seats', 'Live Cockpit Pro', 'Wireless Charging', 'Harman Kardon Audio', 'Gesture Control'],
    chauffeurAvailable: true,
    images: [
      '/cars/bmw-5-series.png',
      '/cars/bmw-5-series.png',
      '/cars/bmw-5-series.png',
    ],
    description: 'The all-new BMW 5 Series (G60) sets a new benchmark for the driving experience in its class. Its Live Cockpit Pro curved display and Harman Kardon surround-sound system transform every ride into a premium event. Whether you\'re heading to a high-stakes client meeting in Casablanca or a gala in Marrakech, the 520d commands respect from the moment it pulls up.',
    shortDesc: 'Sporty executive saloon with cutting-edge tech.',
    available: true,
  },
  {
    id: '3',
    slug: 'range-rover-sport',
    name: 'Range Rover Sport',
    brand: 'Land Rover',
    model: 'Sport HSE',
    year: 2024,
    category: 'suv',
    eventTypes: ['wedding', 'party', 'roadtrip', 'corporate'],
    pricePerDay: 650,
    seats: 5,
    luggage: 4,
    transmission: 'automatic',
    fuelType: 'hybrid',
    features: ['Meridian Sound', 'Pivi Pro Infotainment', 'Panoramic Roof', '4WD', 'Air Suspension', 'Massage Seats'],
    chauffeurAvailable: true,
    images: [
      '/cars/range-rover-sport.png',
      '/cars/range-rover-sport.png',
      '/cars/range-rover-sport.png',
    ],
    description: 'The Range Rover Sport HSE commands every road with an authority that few vehicles can match. Its plug-in hybrid powertrain pairs whisper-quiet electric performance with the legendary 4WD capability Land Rover is famous for. Featuring air suspension, massage seats, and a panoramic roof, it is the prestige SUV that can arrive at a five-star wedding venue or traverse a mountain trail with equal elegance.',
    shortDesc: 'Commanding luxury SUV for any grand occasion.',
    available: true,
  },
  {
    id: '4',
    slug: 'cadillac-escalade',
    name: 'Cadillac Escalade',
    brand: 'Cadillac',
    model: 'Escalade Premium',
    year: 2023,
    category: 'suv',
    eventTypes: ['wedding', 'party', 'airport'],
    pricePerDay: 750,
    seats: 7,
    luggage: 6,
    transmission: 'automatic',
    fuelType: 'petrol',
    features: ['36-inch OLED Display', 'AKG 36-Speaker Audio', 'Power Running Boards', 'Night Vision', 'Heads-Up Display', 'Rear-Seat Entertainment'],
    chauffeurAvailable: true,
    images: [
      '/cars/cadillac-escalade.png',
      '/cars/cadillac-escalade.png',
      '/cars/cadillac-escalade.png',
    ],
    description: 'Nothing announces an arrival quite like the Cadillac Escalade Premium. Its cathedral-like cabin features a sweeping 36-inch OLED display, AKG 36-speaker audio, and handcrafted leather that stretches across three rows. Power running boards deploy automatically to welcome seven passengers. Whether leading a wedding convoy or collecting VIP guests at Mohammed V Airport, the Escalade delivers theatre on wheels.',
    shortDesc: 'Bold American luxury SUV seating 7 in style.',
    available: true,
  },
  {
    id: '5',
    slug: 'porsche-911-cabriolet',
    name: 'Porsche 911 Cabriolet',
    brand: 'Porsche',
    model: '911 Carrera S Cabriolet',
    year: 2024,
    category: 'convertible',
    eventTypes: ['party', 'wedding', 'roadtrip'],
    pricePerDay: 850,
    seats: 2,
    luggage: 1,
    transmission: 'automatic',
    fuelType: 'petrol',
    features: ['Retractable Soft Top', 'Sport Chrono Package', 'Bose Sound', 'Heated Seats', 'Launch Control', 'PASM Active Suspension'],
    chauffeurAvailable: false,
    images: [
      '/cars/porsche-911.png',
      '/cars/porsche-911.png',
      '/cars/porsche-911.png',
    ],
    description: 'There is no more thrilling way to celebrate than behind the wheel of a Porsche 911 Carrera S Cabriolet. Drop the roof and let that iconic flat-six exhaust note serenade the entire boulevard. With 450 hp, Sport Chrono-enhanced launch control, and PASM adaptive suspension perfectly balanced for Moroccan coastal roads, this car does not just transport you — it transforms your entire event into a memory.',
    shortDesc: 'Iconic open-top sports car for pure driving joy.',
    available: true,
  },
  {
    id: '6',
    slug: 'mercedes-sprinter',
    name: 'Mercedes Sprinter VIP',
    brand: 'Mercedes-Benz',
    model: 'Sprinter 319 VIP',
    year: 2023,
    category: 'van',
    eventTypes: ['wedding', 'corporate', 'airport', 'party'],
    pricePerDay: 550,
    seats: 12,
    luggage: 12,
    transmission: 'automatic',
    fuelType: 'diesel',
    features: ['VIP Leather Club Seats', 'Mood Lighting', 'Mini Bar', 'Entertainment System', 'Tinted Windows', 'WiFi'],
    chauffeurAvailable: true,
    images: [
      '/cars/mercedes-sprinter.png',
      '/cars/mercedes-sprinter.png',
      '/cars/mercedes-sprinter.png',
    ],
    description: 'The Mercedes Sprinter 319 VIP redefines what a minibus can be. Step inside to find bespoke leather club seats arranged in a lounge configuration, a chilled mini bar stocked for your event, ambient mood lighting, and an entertainment system to set the tone. All 12 guests travel together in genuine luxury — no compromise, no splitting the party. The vehicle of choice for wedding convoys, executive airport transfers, and corporate hospitality.',
    shortDesc: 'Luxury 12-seat VIP van for stylish group travel.',
    available: true,
  },
  {
    id: '7',
    slug: 'vw-transporter',
    name: 'VW Transporter Shuttle',
    brand: 'Volkswagen',
    model: 'Transporter T7 Shuttle',
    year: 2024,
    category: 'van',
    eventTypes: ['airport', 'corporate', 'roadtrip'],
    pricePerDay: 320,
    seats: 9,
    luggage: 9,
    transmission: 'automatic',
    fuelType: 'diesel',
    features: ['Comfort Seats', 'Climate Control', 'Cruise Control', 'Navigation', 'Rear Camera', 'USB Charging Ports'],
    chauffeurAvailable: true,
    images: [
      '/cars/vw-transporter.png',
      '/cars/vw-transporter.png',
      '/cars/vw-transporter.png',
    ],
    description: 'The all-new VW Transporter T7 Shuttle is German engineering applied to group travel — precise, practical, and genuinely comfortable. Its ergonomic captain seats, dual-zone climate control, and DSG automatic gearbox make light work of Casablanca rush-hour and Saharan highways alike. With 9 seats and 9 bags of luggage capacity, it is the gold standard for airport meet-and-greet services and corporate team transfers.',
    shortDesc: 'Reliable 9-seat shuttle for group transfers.',
    available: true,
  },
  {
    id: '8',
    slug: 'peugeot-208',
    name: 'Peugeot 208',
    brand: 'Peugeot',
    model: '208 Allure',
    year: 2025,
    category: 'economy',
    eventTypes: ['airport', 'corporate', 'roadtrip'],
    pricePerDay: 120,
    seats: 5,
    luggage: 2,
    transmission: 'manual',
    fuelType: 'petrol',
    features: ['i-Cockpit Display', 'Apple CarPlay & Android Auto', 'Climate Control', 'Lane Assist', 'Rear Camera', 'Cruise Control'],
    chauffeurAvailable: false,
    images: [
      '/cars/peugeot-208.png',
      '/cars/peugeot-208.png',
      '/cars/peugeot-208.png',
    ],
    description: 'The 2025 Peugeot 208 Allure is not your average economy car — it is a design statement disguised as a city hatchback. Its signature i-Cockpit architecture places a compact steering wheel below a high-set 3D digital instrument cluster, creating a genuinely futuristic driving position. Seamless Apple CarPlay, automatic climate control, and a frugal 1.2 PureTech engine make it the smartest, most affordable way to navigate Morocco\'s cities in style.',
    shortDesc: 'Stylish modern hatchback with premium tech.',
    available: true,
  },
  {
    id: '9',
    slug: 'opel-corsa',
    name: 'Opel Corsa',
    brand: 'Opel',
    model: 'Corsa GS',
    year: 2025,
    category: 'economy',
    eventTypes: ['airport', 'roadtrip', 'corporate'],
    pricePerDay: 110,
    seats: 5,
    luggage: 2,
    transmission: 'automatic',
    fuelType: 'petrol',
    features: ['IntelliLink Infotainment', 'Wireless CarPlay', 'LED Matrix Headlights', 'Ergonomic AGR Seats', 'Rear Parking Sensors', 'Drive Mode Selector'],
    chauffeurAvailable: false,
    images: [
      '/cars/opel-corsa.png',
      '/cars/opel-corsa.png',
      '/cars/opel-corsa.png',
    ],
    description: 'The 2025 Opel Corsa GS punches well above its price bracket with its signature LED matrix headlights, wireless CarPlay, and AGR-certified ergonomic seats designed for long-haul comfort. The automatic gearbox paired with a Drive Mode Selector lets you dial in precisely the driving character you want — whether that is eco for the highway or sport for winding Rif mountain roads. Great value, zero compromise.',
    shortDesc: 'Efficient German hatchback with modern character.',
    available: true,
  },
  {
    id: '10',
    slug: 'dacia-duster',
    name: 'Dacia Duster',
    brand: 'Dacia',
    model: 'Duster Journey 4x4',
    year: 2024,
    category: 'suv',
    eventTypes: ['roadtrip', 'airport', 'party'],
    pricePerDay: 180,
    seats: 5,
    luggage: 3,
    transmission: 'manual',
    fuelType: 'diesel',
    features: ['4x4 All-Terrain Mode', 'Media Nav Evolution', 'Roof Rails', 'Hill Start Assist', 'Rear Camera', 'USB-C Charging'],
    chauffeurAvailable: false,
    images: [
      '/cars/dacia-duster.png',
      '/cars/dacia-duster.png',
      '/cars/dacia-duster.png',
    ],
    description: 'The Dacia Duster Journey 4x4 was engineered for exactly the kind of terrain Morocco offers: Saharan pistes, High Atlas passes, and everything between. Its dedicated 4x4 all-terrain mode, hill-start assist, and high ground clearance handle unpaved roads that would stop lesser vehicles cold. Yet inside, the Media Nav Evolution system and USB-C charging keep everyone connected. Epic adventure at an honest price — the ultimate road-trip SUV.',
    shortDesc: 'Rugged 4x4 SUV built for Moroccan adventures.',
    available: true,
  },
  {
    id: '11',
    slug: 'dacia-sandero',
    name: 'Dacia Sandero Stepway',
    brand: 'Dacia',
    model: 'Sandero Stepway Expression',
    year: 2024,
    category: 'economy',
    eventTypes: ['airport', 'roadtrip', 'corporate'],
    pricePerDay: 95,
    seats: 5,
    luggage: 2,
    transmission: 'manual',
    fuelType: 'petrol',
    features: ['Media Control via Smartphone', 'Roof Rails', 'Fog Lights', 'Sliding Rear Armrest', 'Start-Stop System', 'Multi-View Camera'],
    chauffeurAvailable: false,
    images: [
      '/cars/dacia-sandero.png',
      '/cars/dacia-sandero.png',
      '/cars/dacia-sandero.png',
    ],
    description: 'The Dacia Sandero Stepway Expression is Morocco\'s most beloved everyday car for a reason — it does everything well without asking much in return. The raised ride height and roof rails give it a practical crossover character, while the smartphone media control system keeps you connected on the move. At 95 MAD per day it is the smartest choice for budget-conscious travellers who still want a modern, capable car for their airport pickup or city-to-coast drive.',
    shortDesc: "Morocco's favourite practical city-to-road car.",
    available: true,
  },
  {
    id: '12',
    slug: 'dacia-logan',
    name: 'Dacia Logan',
    brand: 'Dacia',
    model: 'Logan Expression',
    year: 2024,
    category: 'economy',
    eventTypes: ['airport', 'corporate'],
    pricePerDay: 80,
    seats: 5,
    luggage: 3,
    transmission: 'manual',
    fuelType: 'petrol',
    features: ['Large Boot (510L)', 'MediaNav 8" Display', 'Bluetooth', 'Rear Parking Sensors', 'Speed Limiter', 'USB Charging'],
    chauffeurAvailable: false,
    images: [
      '/cars/dacia-logan.png',
      '/cars/dacia-logan.png',
      '/cars/dacia-logan.png',
    ],
    description: 'The Dacia Logan Expression is the reigning champion of practical value. Its class-leading 510-litre boot swallows airport luggage with ease, while the 8-inch MediaNav touchscreen, Bluetooth, and rear parking sensors keep journeys effortless. The frugal petrol engine keeps running costs ultra-low on long transfers between Moroccan cities. Simple, spacious, and supremely reliable — everything a smart traveller needs.',
    shortDesc: 'Best-value sedan with a huge 510L boot.',
    available: true,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Yasmine Benali',
    avatar: 'https://i.pravatar.cc/80?img=1',
    eventType: 'wedding',
    eventLabel: 'Wedding',
    rating: 5,
    text: 'We booked the Range Rover Sport for our wedding day and it was absolutely perfect. The car was immaculate, the chauffeur was so professional, and it made our photos look stunning. EventWheels made the whole process effortless.',
    location: 'Casablanca',
  },
  {
    id: '2',
    name: 'Karim Mansouri',
    avatar: 'https://i.pravatar.cc/80?img=12',
    eventType: 'corporate',
    eventLabel: 'Corporate Event',
    rating: 5,
    text: 'Used EventWheels for our entire executive team during a conference in Marrakech. The BMW 5 Series fleet looked sharp, the booking process was smooth, and everything ran like clockwork. Will definitely use again.',
    location: 'Marrakech',
  },
  {
    id: '3',
    name: 'Sarah El Fassi',
    avatar: 'https://i.pravatar.cc/80?img=5',
    eventType: 'airport',
    eventLabel: 'Airport Transfer',
    rating: 5,
    text: 'Booked the VIP Sprinter to pick up our 10 guests arriving from Dubai. The driver was waiting at arrivals with a name board, the van was spotless, and our guests were genuinely impressed. Five stars, no question.',
    location: 'Agadir',
  },
  {
    id: '4',
    name: 'Adam Tazi',
    avatar: 'https://i.pravatar.cc/80?img=33',
    eventType: 'party',
    eventLabel: 'Birthday Party',
    rating: 5,
    text: 'Surprised my girlfriend with a Porsche 911 for her 30th birthday — EventWheels handled everything from the booking to a beautiful ribbon on the car. The look on her face was priceless. Highly recommended!',
    location: 'Rabat',
  },
  {
    id: '5',
    name: 'Nadia Cherkaoui',
    avatar: 'https://i.pravatar.cc/80?img=9',
    eventType: 'roadtrip',
    eventLabel: 'Road Trip',
    rating: 4,
    text: 'Rented the Dacia Duster for a 5-day Atlas Mountain road trip with friends. Great value, very comfortable off-road, and the team gave us helpful tips on the route. A fantastic experience for the price.',
    location: 'Fès',
  },
];

export const eventUseCases: EventUseCase[] = [
  {
    id: 'wedding',
    label: 'Weddings',
    icon: '💍',
    tagline: 'Arrive as beautifully as you planned',
    description: 'Your wedding day deserves nothing less than perfection. Our curated fleet of luxury vehicles — complete with professional chauffeurs, decorated interiors, and immaculate presentation — ensures your arrival is as flawless as your celebration.',
    recommendedCars: ['mercedes-e-class', 'range-rover-sport', 'cadillac-escalade'],
  },
  {
    id: 'corporate',
    label: 'Corporate Events',
    icon: '💼',
    tagline: 'Project authority from the moment you arrive',
    description: 'First impressions define business relationships. Whether it\'s a high-stakes client meeting, a corporate gala, or an executive transfer, our premium fleet helps you project the confidence and professionalism your brand deserves.',
    recommendedCars: ['bmw-5-series', 'mercedes-e-class', 'vw-transporter'],
  },
  {
    id: 'airport',
    label: 'Airport Transfers',
    icon: '✈️',
    tagline: 'Meet every guest with style and punctuality',
    description: 'From solo VIP arrivals to large group transfers, we coordinate every detail. Our drivers track flights in real time, handle luggage, and ensure your guests start their visit feeling welcomed and impressed.',
    recommendedCars: ['mercedes-sprinter', 'vw-transporter', 'dacia-sandero'],
  },
  {
    id: 'party',
    label: 'Parties & Celebrations',
    icon: '🎉',
    tagline: 'Make your celebration impossible to forget',
    description: 'Birthdays, bachelorette parties, anniversaries — whatever you\'re celebrating, the right car transforms a good night into an unforgettable one. Choose from eye-catching sports cars, spacious luxury vans, or classic convertibles.',
    recommendedCars: ['porsche-911-cabriolet', 'cadillac-escalade', 'mercedes-sprinter'],
  },
  {
    id: 'roadtrip',
    label: 'Road Trips',
    icon: '🗺️',
    tagline: 'Morocco is yours — drive it in comfort',
    description: 'From the Atlantic coast to the Sahara edge, Morocco\'s roads beg to be explored. Our road-trip fleet offers everything from rugged 4x4s for mountain trails to comfortable estates for long family journeys across the kingdom.',
    recommendedCars: ['dacia-duster', 'range-rover-sport', 'dacia-sandero'],
  },
];

export const getCar = (slug: string): Car | undefined =>
  cars.find((c) => c.slug === slug);

export const getRelatedCars = (car: Car, count = 3): Car[] =>
  cars
    .filter(
      (c) =>
        c.id !== car.id &&
        (c.category === car.category ||
          c.eventTypes.some((e) => car.eventTypes.includes(e)))
    )
    .slice(0, count);

export const categoryLabels: Record<string, string> = {
  sedan: 'Sedan',
  suv: 'SUV',
  convertible: 'Convertible',
  van: 'Van / Minibus',
  sports: 'Sports',
  economy: 'Economy',
};

export const eventLabels: Record<string, string> = {
  wedding: 'Wedding',
  corporate: 'Corporate',
  airport: 'Airport',
  party: 'Party',
  roadtrip: 'Road Trip',
};
